channels:
  - default
  - conda-forge
dependencies:
  - iris
  - netcdftime
  - pandas
  - numpy
  - pip
  - pip:
    - "git+https://github.com/openclimatedata/pymagicc.git@master"
    - matplotlib
    # things we may need later
    # - progressbar2
    # - tables
    # - jupyter_contrib_nbextensions
    # - notebook
    # can change this once the weird failure with jupyter installation
    # goes away, see https://github.com/pypa/pip/issues/5839
    # - ipython<7
    # - prompt-toolkit==1.0.15
